### ISSUE TITLE
Древовидная структура bus

### ISSUE THREAD

**Issue by vvzvlad** [glial-iot/glue_panel#72]
Сложная задача. В bus топики изначально были представлены в виде одномерной таблицы. Теперь хочется показать их в виде древовидной структуры, в которой бы топики могли объединяться вместе, если у них есть в адресе одинаковые части — это надо для представления больших количеств топиков. Бекенд готов, он отдает содержимое bus в виде вот такого json:
[system_bus_action.json.txt](https://github.com/vvzvlad/glue_web_app/files/2249622/system_bus_action.json.txt)

Адрес system_bus_action?action=get_bus_serialized. 

Расположить это на отдельной странице Bus tree. 
Ориентир по внешнему виду:
<img width="1202" alt="bus tree" src="https://user-images.githubusercontent.com/3315944/43528419-964cb310-95b1-11e8-8f1f-c156e510661b.png">

Пример древовидного массива на vue: https://codepen.io/anthonygore/pen/PJKNqa
Компонент: https://github.com/ParadeTo/vue-tree-list
Какая-то крутая по возможностям библиотека: https://amsik.github.io/liquor-tree/
(там есть пример json-viewer, который вполне себе ест этот json: https://amsik.github.io/liquor-tree/#JSON-Viewer)

**Comment by nismangulov** [comment]
@vvzvlad 

Привел демку к адекватному табличному виду, залил в https://github.com/vvzvlad/glue_web_app/pull/81

Данные пока тянутся из захардкоженного json, так как пока не знаю, откуда брать реальные данные. Ещё скорее всего могут быть проблемы с реактивностью - могут сбрасываться раскрытые узлы при обновлении данных. Это нужно смотреть и дорабатывать уже на живом бекенде.

**Comment by vvzvlad** [comment]
Тогда сделай запрос раз в секунду с адреса system_bus_action?action=get_bus_serialized, а сейчас напишу инструкцию, как запустить бекенд и получить из него данные. 
И перенеси это либо на отдельную страницу, либо сделай переключалку "tree view/linear view" в bus.

**Comment by nismangulov** [comment]
> сделай переключалку "tree view/linear view" в bus

Да, норм идея. Давай сделаем переключатель с запоминанием в локалсторадж.

**Comment by vvzvlad** [comment]
И сразу правки: 
1) Убрать уровни root и bus, дерево должно начинаться с первого уровня топиков. 
2)Между строчками нужен разделитель, как в обычной таблице: полоска

А вообще офигенно выглядит.

**Comment by nismangulov** [comment]
@vvzvlad 

Залил в https://github.com/vvzvlad/glue_web_app/pull/86 апдейт - сделал переключатель с локалстораждем, добавил разделители, подключил работу с апи. Но есть пара но:

1. уровень `root` убрал, но `bus` красиво убрать не получится - у дерева должен быть только один корень. получится только если рисовать кучу деревьев - но можем нахватать багов. сделать можно, но только после фикса следующего косяка;

2. компонент совсем не умеет работать с реактивностью. то есть при каждом обновлении данных раскрытые ноды дерева сворачиваются обратно. мне кажется это можно починить - но нужно ещё немного времени продумать, как доработать обновление данных.

**Comment by vvzvlad** [comment]
> у дерева должен быть только один корень. получится только если рисовать кучу деревьев - но можем нахватать багов.

Так пусть будет один. Его же можно просто не показывать, простой проверкой — если корень, то не рисуем?

>мне кажется это можно починить - но нужно ещё немного времени продумать, как доработать обновление данных.

А если в отдельной таблице хранить статус открыто/закрыто каждого элемента дерева?

**Comment by nismangulov** [comment]
@vvzvlad 

Залил фикс сворачивающегося дерева в #96

> А если в отдельной таблице хранить статус открыто/закрыто каждого элемента дерева?

Это можно делать, но это не поможет. По хорошему, судя по документации библиотеки, если нужна реактивность - нужно строить диффы и вычислять, куда прикреплять/откуда удалять узлы. В нашем случае это будет очень долго и больно. Сейчас попробовал мержить объекты с деревьями, давай посмотрим, как будет работать.

**Comment by vvzvlad** [comment]
А что сейчас не работает?

**Comment by nismangulov** [comment]
@vvzvlad 

> А что сейчас не работает?

Теперь всё работать должно :) А до сегодняшнего пуллреквеста плохо работало обновление дерева - при запросе данных все узлы сворачивались обратно.

Убрал у дерева корень - вроде ничего не сломалось, все работает, библиотека все ок отрисовывает. Больше вопросов по этой задаче вроде нет.

**Comment by vvzvlad** [comment]
Сделай тогда перезагрузку всего дерева при удалении, пусть с потерей раскрытых топиков, чтобы оно работало без глюков.

**Comment by vvzvlad** [comment]
Кстати, мы не учли, что у корневых топиков тоже могут быть значения: 
![image](https://user-images.githubusercontent.com/3315944/44025962-3512aca6-9efa-11e8-9d1c-e39d79bc7df2.png)
/test/ является родителем /test/2, но у /test/ тоже есть значение. Поэтому я переделал структуру json-а, теперь данные топика лежат в __data__, а все, что не лежит в __data__ — то дети:
![image](https://user-images.githubusercontent.com/3315944/44026032-7275b58e-9efa-11e8-9bfa-d86946cff8ea.png)
Прикладываю пример json-a:
[system_bus_v2.json.txt](https://github.com/vvzvlad/glue_web_app/files/2282570/system_bus_v2.json.txt)

Новый формат доступен по адресу system_bus?action=get_bus_serialized_v2, новая версия бекенда уже в мастере.

**Comment by nismangulov** [comment]
@vvzvlad 

Ещё пару апдейтов залил в #109.

Сделал перезагрузку всего дерева при удалении, но с get_bus_serialized_v2 есть проблема - теперь компонент для отрисовки дерева (liquor-tree) всегда отображает на всех нодах дерева значки, даже когда у ноды нет детей. Чтобы это пофиксить - надо к форкать репозиторий с этим компонентом и править их код. Если мешает - давай так это пофиксим.

![image](https://user-images.githubusercontent.com/6184888/44084856-b7eed912-9fd9-11e8-86c3-e35d8c640623.png)

**Comment by vvzvlad** [comment]
Да, давай форкнем, добавим в проект и уберем этот значок у листьев дерева.

**Comment by nismangulov** [comment]
@vvzvlad 

Перенес компонент в наше репо, пофиксил значок у листьев дерева. Залил в #140.

Но - после переноса обнаружился один баг в консоли. Насколько я понял - он связан с мультиселектом листьев дерева, но мы его в проекте не используем. Пытался пофиксить его - за ним по цепочке вылезает ещё пачка багов, на которых можно зависнуть ещё на несколько часов. Отсюда вопрос - критична ли нам ошибка в консоли? Или пока пусть висит?

![image](https://user-images.githubusercontent.com/6184888/44641260-fc494580-a9e7-11e8-99df-708556ea3b39.png)
